steps:
- id: 'build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'IMAGE_NAME=gcr.io/$PROJECT_ID/hello-world:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/hello-world:$BUILD_ID', '.']
  timeout: 180s
- id: 'push image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-world:$BUILD_ID']
- id: 'apply to k8s'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - apply
  - '-f'
  - 'k8s/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'