apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud-hello-world-deployment
  labels:
    app: gcloud-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcloud-hello-world
  template:
    metadata:
      labels:
        app: gcloud-hello-world
    spec:
      containers:
      - name: web
        image: IMAGE_NAME
        ports:
        - containerPort: 80
